### ISSUE TITLE
Improve toBattleType function so that unequal status values for Multi treated as failure cases

### ISSUE THREAD

**Issue by jpierson** [phated/metax-deck-builder#18]
As discussed, it would be nice to guard against cases where unequal status values in any two categories are not treated as a Multi case but instead signal an error case that should be handled in the case where it happens.

See section of [toBattleType lines 556-574 of Main.elm](https://github.com/phated/metax-deck-builder/blob/d5204435fd1fe58398b90c814e181e3e3c85aadb/src/Main.elm#L556-L574).

**Comment by jpierson** [comment]
I'm not familiar with testing practices in Elm so in the meantime I pulled the relevant parts into [an Ellie](https://ellie-app.com/82sC6pb5Wa1/0) that has the majority of the interesting cases laid out to ensure the right answer is being yielded for the possible inputs as it is refactored.

https://ellie-app.com/82sC6pb5Wa1/0

**Comment by jpierson** [comment]
With these changes the possible issues are more obvious in the output since Single and Multi stats are specifically encoded with their values preserved. If this direction is of interest my guess the next step would be to put make the unequal cases return Nothing probably via a pattern match on Multi in a separate shared function.

https://ellie-app.com/82sC6pb5Wa1/3

**Comment by phated** [comment]
I think that 2nd ellie link is getting close to a solution.  However, the "Multi" concept in the game allows for a dual type or all three types combined.  Also, a "Mutli" must have the same rank for each stat type (strength, intelligence, special) - this is hardcoded into the rules so it's unlikely to change between card sets.

**Comment by phated** [comment]
It would also be **really** nice to guard or range the `Int` to 1-7 (another hardcoded constraint in the rules).

**Comment by phated** [comment]
I now do this validation when decoding stats now - implementation at https://github.com/phated/metax-deck-builder/blob/master/src/Component/Card/Stats.elm#L131-L194
